name: CI/CD Pipeline with Incremental Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: launch-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Identify changed files
        id: git-diff
        run: |
          echo "Changed files: "
          git diff --name-only HEAD^ HEAD
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')"
# tr = translate
# \n = new line
# ' ' = space character
# main purpose is looping

      - name: Deploy all files (if no changes detected)
        if: steps.git-diff.outputs.files == ''
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Deploy only changed files
        if: steps.git-diff.outputs.files != ''
        run: |
          for file in ${{ setps.git-diff.outputs.files }}; do
            scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} $file ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}/
          done
# !='' condition for github action output is not empty
# scp = securely copy files between local machine to remote machine, it is for ssh

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
        
      - name: Set up python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file found"
      - name: Execute the python script
        run: python3 tar.py

      - name: Capture the output
        run: python3 tar.py > output.log

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with: 
          name: execution-output
          path: output.log
